name: ideasearch-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - streamlit>=1.28.0
  - plotly>=5.17.0
  - pandas>=2.0.0
  - numpy>=1.21.0
  - matplotlib>=3.7.0
  - scipy>=1.11.0
  - pyyaml>=6.0.1
  - toml>=0.10.2
  - pip
  - pip:
    - -i https://pypi.org/simple/
    - streamlit-drawable-canvas>=0.9.2
    - pywheels>=0.7.6.2
    - ideasearch==0.0.1
    - ideasearch-fit>=0.0.4
    # 开发依赖
    - pytest>=8.0.0
    - black>=23.0.0
    - ruff>=0.1.0
    - flake8>=6.0.0
    - mypy>=1.0.0
